- gc/benches/alloc_in_a_loop.rs
- gc/src/gc.rs
This is still very naive, butavoids quadratic behaviour, by collecting
exponentially rarely as the heap grows. This cuts the run time of the
included `keep_10000` benchmark from an (estimated) 300 ms to ~1ms.
The failure case of the naive strategy is how often it collects when
growing to some heap size N (e.g. a graph structure with N nodes): if
the N is larger than the threshold, then at some point the live heap
size will have passed the threshold and every allocation will be trying
to collect. Each collection does O(size of heap) work as it scans the
heap, and each allocation is linearly increasing the size of heap, so to
get to a heap size of N, we do O(N) collections that involve O(N) work:
O(N^2).
By collecting exponentially rarely, getting to a heap size of N takes
one collection of …
> Use a non-quadratic collection frequency.

- gc/Cargo.toml
It didn't appear to be used. Since compiletest also doesn't support Windows directly (without MSYS), this makes testing on Windows easier.
> Remove compiletest dependency

- gc/src/lib.rs
- gc/src/trace.rs
- gc_plugin/src/lib.rs
1. Derive `Debug` for `Gc<String>`
2. Derive `Trace` for `bool` and `usize`
3. Import `syntax_ext` and `rustc_plugin`, so it can compile on the nightly `rustc`
> Some run-of-the-mill fixes

- gc/src/lib.rs
- gc_plugin/src/lib.rs
The `unify_fieldless_variants` stuff comes from here: https://github.com/rust-lang/rust/commit/0eeb14eaba04025aa8a4612e1935f04f2ca3fb6b
I'm still not 100% clear on what it does, but I'm fairly certain the safest thing is to leave it off.
I'm also not sure why I have to export trace and not just use the existing `pub use trace::Trace`, but it appears to not compile if you don't export the `trace` module.
> Updated gc_plugin to breaking changes in the nightly and fixed export of trace in gc

- gc/src/gc.rs
- gc/src/lib.rs
> Abort on root count overflows

- gc/src/gc.rs
- gc/src/lib.rs
- gc/src/test.rs
This causes us to panic whenever accessing a potentially invalid
GcBox<T>, rather than only when accessing the value stored within this
GcBox<T>.
Fixes #36 and #37
> Panic in Gc<T>.inner() instead of GcBox<T>.data()

- gc/src/lib.rs
> Use alignment to store `Gc`'s rooted flag

- .travis.yml
- gc/Cargo.toml
- gc/benches/alloc_in_a_loop.rs
- gc/src/gc.rs
- gc/src/lib.rs
- gc/src/stable.rs
- gc/src/trace.rs
- gc/tests/finalize.rs
- gc/tests/gc_semantics.rs
- gc/tests/gymnastics_cycle.rs
- gc/tests/trace_impl.rs
- gc_derive/src/lib.rs
- upload-docs.sh
In order to do this, when `--features nightly` is not enabled:
- There is no default implementation of `Finalize`, meaning that it
must be manually implemented (for example, by the new
`#[derive(Finalize)]` custom derive implementation).
- There is no support for `CoerceUnsize` so it is hard (impossible?) to
create `Gc<T> where T: ?Sized`.
- The tree now contains dummy no-op implementations of `Shared<T>` and
`NotNull<T>`, which are used in stable rust.
Fixes #46
> Add support for stable rust

- gc/Cargo.toml
- gc/src/gc.rs
- gc/src/lib.rs
- gc/src/stable.rs
- gc_derive/Cargo.toml
Changed in https://github.com/rust-lang/rust/pull/41064
Fixes #55
> Update for new Shared and NonZero API.

- gc/src/lib.rs
- gc/src/stable.rs
- gc/src/trace.rs
- gc/tests/i128.rs
`{i,u}128` should be feature-gated behind a `nightly` feature.
There should be a decision about what the largest tuple arity to support will be -- compiling the impls for each different length it can increase compile times a lot.
For reference, `std` provides trait impls for up to 31-item arrays and 12-tuples.
Does it make sense to make a custom singly-linked `GcLinkedList` type instead of or in addition to having `Gc<LinkedList>` be supported?
~## [`std::ffi`](https://doc.rust-lang.org/std/ffi/)~
- ~[`CString`](https://doc.rust-lang.org/std/ffi/struct.CString.html)~
- ~[`OsString`](https://doc.rust-lang.org/std/ffi/struct.OsString.html)~
~There should probably be some directions with regards to FFI and GC; does e.g. [`CString::into_raw`](https://doc.rust-lang.org/std/ffi/struct.CString.ht …
> Adds impls for more types in std

- gc/src/lib.rs
PR for #62. Aims to implement these methods:
```rust
fn into_raw(gc: Gc<T>) -> *const T { ... }
unsafe fn from_raw(ptr: *const T) -> Gc<T> { ... }
```
which are analogous to [`Rc::into_raw`](https://doc.rust-lang.org/std/rc/struct.Rc.html#method.into_raw), [`Rc::from_raw`](https://doc.rust-lang.org/std/rc/struct.Rc.html#method.from_raw).
Mostly just following the code from [`alloc/rc.rs`](https://doc.rust-lang.org/src/alloc/rc.rs.html#367).
> Add raw pointer interface

- gc/tests/finalize.rs
- gc/tests/gc_semantics.rs
- gc_derive/Cargo.toml
I have noticed that in Boa, we have duplicated versions of these dependencies due to `gc` not being up to date. It seems that the update is backwards compatible and nothing breaks.
This also fixes #79, so I added a test for it.
> Upgraded syn/quote dependencies for gc_derive

- gc/Cargo.toml
- gc/benches/alloc_in_a_loop.rs
- gc/src/gc.rs
- gc/src/lib.rs
- gc/src/trace.rs
- gc/tests/finalize.rs
- gc/tests/gc_semantics.rs
- gc/tests/gymnastics_cycle.rs
- gc/tests/i128.rs
- gc/tests/trace_impl.rs
- gc_derive/Cargo.toml
- gc_derive/src/lib.rs
This PR adds the `edition = "2018"` setting to `Cargo.toml`, fixes all non-2018 edition idioms and a bunch of other Clippy lints, making the code more "idiomatic". I also ran `cargo fmt` to follow Rust code formatting conventions.
> Updated code to 2018 edition

- gc/src/trace.rs
We now have `NonZero` and more `Atomic` integers in the standard library, so I added the `Trace` and `Finalize` implementation for them.
I think this should be ready to add it to a new release in crates.io :)
> Added `Trace` and `Finalize` for more std types

- gc/Cargo.toml
- gc/src/lib.rs
This adds the `derive` feature, similarly to how `serde` among others do it. This allows not depending on `gc_derive` from other crates, and we can just add the `derive` feature when importing the crate.
> Added "derive" feature to avoid importing two crates

- gc/src/trace.rs
- gc/tests/trace_impl.rs
This allows deriving `Trace` easily in any type where an inner member is a `Box<str>` which provides some space optimizations with respect to `String`.
> Added `Trace` implementation for `Box<str>`

- gc/src/lib.rs
Implements `Display` for `GcCellRef<T>` and `GcCellRefMut<T>` when `T: Display`
> Added `Display` implementation for `GcCellRef` and `GcCellRefMut`

- gc/src/lib.rs
- gc/tests/gc_semantics.rs
Since the low bit of `ptr_root` stores whether the reference is rooted, it should be ignored in `ptr_eq()`
> Fix ptr_eq() on rooted and unrooted references

- gc/src/gc.rs
- gc/src/lib.rs
Rust doesn’t guarantee that fat pointer comparison works as expected due to duplicated vtables:
https://github.com/rust-lang/rust/issues/46139
> Ignore fat pointer vtables for Gc::ptr_eq

- gc/src/lib.rs
The `T: Trace` bound unnecessarily prohibited some valid uses of `GcCellRef::map` (with `#[unsafe_ignore_trace]`).
I wanted to remove `T: Trace` from `GcCellRefMut<T>` too, but it currently uses `T: Trace` in a way that seems to be incorrect (#117).
> Remove T: Trace bound from GcCellRef<T>; add GcCellRef::clone

- gc/tests/gc_semantics.rs
From `cd gc; cargo test --features=nightly`:
```
warning: trait objects without an explicit `dyn` are deprecated
--> gc/tests/gc_semantics.rs:260:27
|
260 |     fn use_trait_gc(x: Gc<Foo>) {
|                           ^^^ help: use `dyn`: `dyn Foo`
|
= note: `#[warn(bare_trait_objects)]` on by default
warning: trait objects without an explicit `dyn` are deprecated
--> gc/tests/gc_semantics.rs:265:20
|
265 |     let gc_foo: Gc<Foo> = gc_bar.clone();
|                    ^^^ help: use `dyn`: `dyn Foo`
```
> Fix deprecated trait object syntax warnings

- gc/src/lib.rs
- gc/tests/from_raw.rs
The recovered `Gc` is not inside a `GcBox` on the heap, so it must be set as a root (like it must have been when it was originally passed to `Gc::into_raw`). Otherwise, putting it into another `Gc` will panic with “`Can't double-unroot a Gc<T>`”.
> Gc::from_raw: Set the Gc as a root

- gc/src/lib.rs
- gc/tests/gc_cell_ref.rs
> GcCellRefMut::drop: Unroot the right value after GcCellRefMut::map

- gc/src/lib.rs
I converted this from `feature(optin_builtin_traits)` in #111, but in fact this has been unused since #51 removed the explicit negative impls for `!Send` and `!Sync`.
> Remove unused feature(auto_traits)

- README.md
- gc/src/lib.rs
- gc/src/trace.rs
- gc/tests/finalize.rs
- gc/tests/gc_semantics.rs
- gc/tests/gymnastics_cycle.rs
- gc/tests/trace_impl.rs
- gc/tests/unsized.rs
`feature(specialization)` as currently implemented in nightly Rust is known to be unsound.
Furthermore, using specialization for `Trace` was also forcing any downstream crate that implements `Trace` to itself enable `feature(specialization)`. This made turning on the `nightly` crate feature a backwards-incompatible change that violates additivity of features, and would cause compilation problems under feature unification.
Fixes #128.
> Remove feature(specialization)

- gc/src/gc.rs
- gc/src/lib.rs
The claim “Because it is `?Sized`, it will always be the last field in memory” was not reliable: the `?Sized` type may in fact be `Sized` (which the compiler will know after monomorphization), and in any case, the language provides no guarantees about the layout of `repr(Rust)` structs.
Switch `GcBox` to `repr(C)`, and rewrite the layout computation based on `Layout::extend`, which has a [documented guarantee](https://doc.rust-lang.org/std/alloc/struct.Layout.html#method.extend) to match the layout of `repr(C)` structs.
(`RcBox` in the standard library [is `repr(C)`](https://doc.rust-lang.org/1.49.0/src/alloc/rc.rs.html#273-281) for the same reason.)
Cc @ravern
> Gc::from_raw: Rely only on documented guarantees to compute layout

- gc/tests/derive_bounds.rs
- gc_derive/src/lib.rs
Deriving `Trace` for a generic `struct` only requires a `Trace` bound on all its field types. There’s no reason to also add a `Trace` bound for all its generic parameters.
Fixes #67.
> Don’t derive bogus generic bounds

- gc_derive/src/lib.rs
Since the object finalizer, if any, probably uses the subobjects, we want to run it before the subobjects are finalized.
> gc_derive: Move object finalizer before subobject finalizers

- gc/tests/derive_bounds.rs
This became unnecessary upon the combination of #113 with #129.
> Remove unnecessary feature(specialization) from test

- gc/src/gc.rs
> Just collect on GcState::drop, to avoid use after free

- gc/src/trace.rs
- gc/tests/phantom_data.rs
I knew I forgot something in #58...
Also fixes a typo.
> Impls Finalize, Trace for PhantomData and Rc<[T]>

- .travis.yml
- gc/Cargo.toml
- gc/src/lib.rs
- gc/src/serde.rs
- gc/tests/serde.rs
This is done with an optional dependency, so it shouldn't add any bloat for non-serde-using users.
> Adds serde support.

- gc/Cargo.toml
- gc/src/gc.rs
- gc/src/lib.rs
For configuration and statistics
Current hard-coded INITIAL_THRESHOLD is very low for project i use this for (https://github.com/CertainLach/jrsonnet/), also garbage collection on thread exit takes too long for short-running CLI app
> Expose GcState internals

- gc/src/gc.rs
Should reduce memory footprint. I ran the benchmarks with `cargo +nightly bench` and didn't notice any slowdown, at least on my arch (x86_64-pc-windows-msvc).
Before:
```
test discard_100   ... bench:      12,092 ns/iter (+/- 612)
test discard_10000 ... bench:   1,197,697 ns/iter (+/- 26,895)
test keep_100      ... bench:      10,594 ns/iter (+/- 284)
test keep_10000    ... bench:     975,823 ns/iter (+/- 42,083)
```
After:
```
test discard_100   ... bench:      11,111 ns/iter (+/- 217)
test discard_10000 ... bench:   1,111,062 ns/iter (+/- 35,206)
test keep_100      ... bench:      10,945 ns/iter (+/- 773)
test keep_10000    ... bench:   1,052,570 ns/iter (+/- 53,772)
```
Incrementing and decrementing roots requires some more bit operations but hopefully those are pretty cheap? Also …
> Store "marked" flag in high bit of "roots" counter

- gc/src/trace.rs
- gc/tests/trace_impl.rs
I’m not sure if these impls would work with a better tracing algorithm, but they do not work correctly with this one.
```rust
let r = Rc::new(Gc::new(()));
Gc::new((Rc::clone(&r), r));
// → thread 'main' panicked at 'Can't double-unroot a Gc<T>'
```
Fixes #134.
I’m open to other suggestions, but I suspect the right way to support `Rc<T>` would be with a trait that marks `T` as containing no `Gc` dependencies (#109). Meanwhile, a user who needs such an `Rc<T>` can `#[unsafe_ignore_trace]`.
> Remove Trace implementation for Rc

- gc/src/trace.rs
- gc/tests/phantom_data.rs
- gc/tests/unsized.rs
- `impl<T: Trace> Trace for Box<[T]>` →
`impl<T: Trace> Trace for [T]`
- `impl Trace for Box<str>` →
`impl Trace for str`
- `impl<T> Trace for PhantomData<T>` →
`impl<T: ?Sized> Trace for PhantomData<T>`
> Generalize Trace impls for unsized types

- gc/src/lib.rs
`cargo miri test` was unhappy about it.
> Avoid memory leak in Gc::into_raw doctest

- gc/src/lib.rs
This had been using pointer trickery to temporarily duplicate a mutable reference, which Miri detected as undefined behavior.
> Fix undefined behavior in GcCellRefMut::map

- Cargo.toml
- gc/Cargo.toml
- gc/tests/derive_bounds.rs
- gc/tests/finalize.rs
- gc/tests/gc_semantics.rs
- gc/tests/gymnastics_cycle.rs
- gc/tests/trace_impl.rs
- gc/tests/unsized.rs
Otherwise `cargo test --all-features` enables it anyway and breaks with ``error[E0252]: the name `Trace` is defined multiple times``.
> Enable the derive feature when testing

- gc/src/gc.rs
- gc/src/lib.rs
- gc/tests/from_box.rs
This is especially useful on nightly, where it works for unsized trait objects.
(Unsized slices cannot be supported with the current design, as there’s no conversion from `[T]` to `dyn Trace`: https://github.com/Manishearth/rust-gc/issues/2#issuecomment-1360513696.)
Fixes #72.
> Implement From<Box<T>> for Gc<T>

- gc/src/gc.rs
- gc/src/lib.rs
- gc/src/serde.rs
- gc/tests/gc_self_method.rs
This requires `#![feature(arbitrary_self_types)]` and nightly 2023-01-27 or later for https://github.com/rust-lang/rust/pull/97373.
> Allow trait objects with methods on `self: Gc<Self>` on nightly

- gc/src/lib.rs
- gc/tests/ignore_trace.rs
Ordinarily, objects dropped during collections would only contain unrooted `Gc` pointers. But with `#[unsafe_ignore_trace]` it’s possible to smuggle a rooted `Gc` pointer into the heap. When we collect a rooted `Gc` pointer, we need to dereference it in order to unroot its contents. This should be safe because the associated allocation cannot have been collected while the `Gc` is rooted.
Fixes an `assertion failed: finalizer_safe()` panic in the included test case (refs #52).
> Allow dereferencing a rooted Gc during collection

- gc/Cargo.toml
- gc_derive/Cargo.toml
A bump for crates.io.
I haven't actually used this at this point, so I don't know if this is a good state to release, but since there haven't been any commits in a couple months so I assume it's relatively stable.
> Release 0.5.0

- gc/src/lib.rs
Simply add `#[track_caller]` to the `borrow` and `borrow_mut` of `GcCell` so that the source will change to the file that call the method instead of the file of the method when they fail
For example
```
use gc::*;
#[test]
fn test_track_caller() {
let cell = GcCell::new(1);
let _borrow = cell.borrow();
let _borrow_mut = cell.borrow_mut();
}
```
Before
```
running 1 test
thread 'test_track_caller' panicked at C:\Develop\Projects\Rust\rust-gc\gc\src\lib.rs:550:23:
GcCell<T> already borrowed
stack backtrace:
0: rust_begin_unwind
at /rustc/6ef7d16be0fb9d6ecf300c27990f4bff49d22d46/library\std\src/panicking.rs:617:5 
1: core::panicking::panic_fmt
at /rustc/6ef7d16be0fb9d6ecf300c27990f4bff49d22d46/library\core\src/panicking.rs:67:14
2: core::panicking::panic_display
at …
```
> Add `#[track_caller]` to the `borrow` and `borrow_mut` of `GcCell`

- gc_derive/Cargo.toml
- gc_derive/src/lib.rs
Updating synstructure seems to fix this warning by not giving the global throwaway constants unique names.
Fixes #174.
> Fix non-local impl warning

- gc_derive/Cargo.toml
This hasn’t been directly used since #64.
> Remove syn

- gc/src/gc.rs
```
warning: initializer for `thread_local` value can be made `const`
--> gc/src/gc.rs:29:52
|
29 | thread_local!(pub static GC_DROPPING: Cell<bool> = Cell::new(false));
|                                                    ^^^^^^^^^^^^^^^^ help: replace with: `const { Cell::new(false) }`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#thread_local_initializer_can_be_made_const
= note: `#[warn(clippy::thread_local_initializer_can_be_made_const)]` on by default
```
> Fix clippy::thread_local_initializer_can_be_made_const

- gc/src/lib.rs
> Add `GcCellRef::filter_map`, `GcCellRefMut::filter_map`

- README.md
- gc/src/trace.rs
These are already handled by `Trace::finalize_glue`; fixes #182
The macro `#[derive(Finalize)]` was already correctly generating empty `Finalize` implementations.
> Remove finalizer method bodies and bounds from implementations for standard library types
